In [34]:
from pypfopt.expected_returns import mean_historical_return
from pypfopt.risk_models import CovarianceShrinkage
import numpy as np
import pandas as pd
import cvxpy as cp
from copy import copy, deepcopy


In [35]:
n=4
m=2
p=1

In [36]:
ds = []

In [ ]:
A_q = np.random.rand(n, n)
Q = np.dot(A_q.T, A_q) + n * np.eye(n) 
c = np.random.uniform(-1, 1, n)
bounds = [(-1, 1) for _ in range(n)]
x_feasible = np.random.uniform(-0.9, 0.9, n)
A = np.random.uniform(-1, 1, (m, n))
G = np.random.uniform(-1, 1, (p, n))
h = np.dot(G, x_feasible)
b = np.dot(A, x_feasible) + np.random.uniform(0.1, 1.0, m)

In [37]:
for i in range(1):
	
	
	
	
	x = cp.Variable(n)
	constraints = [A@x <= b, G@x == h,np.identity(n)@x <= np.ones(n), np.identity(n)@x >= -np.ones(n)]
	prob = cp.Problem(cp.Minimize(0.5*cp.quad_form(x, Q) + c.T@x), constraints)
	prob.solve()
	if prob.status == 'optimal': ds.append((b, x.value))
	

In [39]:
A

array([[-0.72142756, -0.55637699,  0.88379704, -0.67737616],
       [-0.94878079,  0.76248755,  0.57293348, -0.67290018]])

In [38]:
ds

[(array([-0.22633813, -0.47023235]),
  array([ 0.08489935, -0.28807553, -0.4175564 ,  0.24623117]))]

In [25]:
prob.status

'optimal'

In [26]:
x.value

array([-0.1723105 , -0.17500188,  0.82002068,  0.04322235])

In [27]:
from pickle import dump
dump(ds, open("cqp.pkl", "wb"))