In [20]:
from pypfopt.expected_returns import mean_historical_return
from pypfopt.risk_models import CovarianceShrinkage
import numpy as np
import pandas as pd
import cvxpy as cp
import torch
from copy import copy, deepcopy


In [21]:
np.random.seed(42)

In [22]:
n=10

In [23]:
ds = []

In [24]:
a_min = 0.7
a_var = 0.3

b_min = 0.1
b_var = 0.4

r_min = 0.0
r_var = 1.0

x_0_min = 0.0
x_0_var = 1.0

x_ref_min = 0.0
x_ref_var = 1.0

In [25]:
for i in range(1000):
	
	a=a_var*np.random.rand() + a_min
	b=b_var*np.random.rand() + b_min
	r = r_var*np.random.rand() + r_min
	x_0=  x_0_var*np.random.rand() + x_0_min
	x_ref = x_ref_var*np.array([np.random.rand()]*(n)) + x_ref_min
	

	L = r * np.identity(n)
	I = np.identity(n)
	A = np.array([a**(i+1) for i in range(n)])
	B = np.array([[a**(i-1) * b for i in range(j, 0, -1)] + [0]*(n-j) for j in range(1, n+1)])

	u = cp.Variable(n)
	constraints = [u <= np.ones(n), -u <= np.zeros(n), (A*x_0 +B@u) <= np.ones(n), -(A*x_0 +B@u) <= np.zeros(n)]
	prob = cp.Problem(cp.Minimize(cp.quad_form(A*x_0 +B@u - x_ref, I) + cp.quad_form(u, L)), constraints)
	prob.solve()
	if prob.status == 'optimal': 
		X = np.array([2*(a - a_min)/a_var -1, 2*(b - b_min)/b_var - 1, 2*(r - r_min)/r_var - 1, 2*(x_0-x_0_min)/x_0_var-1, 2*(x_ref[0]-x_ref_min)/x_ref_var -1])
		ds.append([X, u.value])
	

In [5]:
import torch
torch.stack(([torch.zeros(64),torch.ones(64)], [torch.zeros(64),torch.ones(64)]), 1).shape

TypeError: expected Tensor as element 0 in argument 0, but got list

In [26]:
from pickle import dump
dump(ds, open("mpc.pkl", "wb"))

In [27]:
h = 0.01*np.random.rand() + 0.9

In [28]:
(h - 0.9)/0.01

0.39363552027744664

In [29]:
ds[0]

[array([-0.25091976,  0.90142861,  0.46398788,  0.19731697, -0.68796272]),
 array([-1.91062765e-23,  8.59048854e-24, -4.32526161e-23, -2.38765867e-23,
        -1.23418140e-23,  9.32580229e-03,  2.80529280e-02,  3.52331447e-02,
         3.39629952e-02,  2.36947145e-02])]

In [30]:
u.value

array([ 5.79305138e-23,  3.02001989e-23,  5.80117435e-23,  2.57773545e-24,
       -3.31000664e-24, -4.34200912e-24, -7.21154871e-24, -3.70132630e-24,
       -1.82119434e-25,  2.47927123e-04])

In [31]:
prob.status

'optimal'

In [32]:
lambda_ = torch.tensor(constraints[1].dual_value)

In [33]:
nu = torch.tensor(constraints[0].dual_value)

In [34]:
rho = torch.tensor(constraints[2].dual_value)

In [35]:
mu = torch.tensor(constraints[3].dual_value)

In [36]:
def grad_cost(U, x_t, x_ref, a, b, q, r):
	grad = torch.zeros_like(U)
	x = x_t
	for k in range(n):
		U_t = U[k].squeeze()
		x_next = a * x + b * U_t
		grad[k] = 2 * b * q * (x_next - x_ref[k].squeeze()) + 2 * r * U_t
		x = x_next
	return grad

In [37]:
def kkt_loss(U, lambda_, mu, nu, rho, x_t, x_ref, a, b, q, r):
		U_min = 0.0
		U_max = 1.0
		T_min = 0.0
		T_max = 1.0

		# Violazione della stazionarietà
		grad_J = grad_cost(U, x_t, x_ref, a, b, q, r)
		grad_ineq_control = lambda_ - mu
		grad_ineq_state = -b * nu + b * rho
		stationarity_violation = (grad_J + grad_ineq_control + grad_ineq_state).pow(2).sum()

		# Violazione della primal feasibility (controlli e stati)
		control_feasibility = (torch.max(U_min - U, torch.zeros_like(U)) + torch.max(U - U_max, torch.zeros_like(U))).pow(2).sum()

		x = copy(x_t)
		state_feasibility = 0
		for k in range(n):
			U_t = U[..., k].squeeze()
			x = copy(a * x + b * U_t)
			state_feasibility += (torch.max(T_min - x, torch.zeros_like(x)) + torch.max(x - T_max, torch.zeros_like(x))).pow(2).sum()

		# Violazione della complementarità
		comp_control = lambda_ * (U - U_min) + mu * (U_max - U)
		comp_state = 0
		x = copy(x_t)
		for k in range(n):
			U_t = U[k].squeeze()
			x_next = a * x + b * U_t
			nu_t = nu[k].squeeze()
			rho_t = rho[k].squeeze()
			comp_state += (nu_t * (T_min - x_next) + rho_t * (x_next - T_max)).pow(2).sum()
			x = copy(x_next)
		comp_loss = comp_control.pow(2).sum() + comp_state

		# Violazione della dual feasibility

		# Somma delle violazioni
		return grad_J, stationarity_violation, control_feasibility,state_feasibility,  comp_loss

In [38]:
kkt_loss(sol, lambda_, mu, nu, rho, t, t_ref, a, b, torch.tensor(1), pen)

NameError: name 'sol' is not defined

In [ ]:
grad = torch.zeros_like(sol)
x = copy(t)
for k in range(n):
	U_t = copy(sol[k].squeeze())
	x_next = a * x + b * U_t
	grad[k] = 2 * b  * (x_next - t_ref[k].squeeze()) + 2 * pen * U_t- b*nu[k]
	x = copy(x_next)

In [ ]:
lambda_

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [ ]:
sol

tensor([0.3827, 0.3616, 0.3281, 0.2713, 0.1726], dtype=torch.float64)

In [ ]:
grad

tensor([1.0003e-01, 9.0769e-02, 7.5044e-02, 4.7745e-02, 4.8572e-17],
       dtype=torch.float64)

In [ ]:
pen

0.17584272646532612

In [ ]:
sol[0]

tensor(0.3827, dtype=torch.float64)

In [ ]:
a * t + b * sol[0]

tensor(0.3484, dtype=torch.float64)

In [ ]:
t_ref[0].squeeze()

0.4382834245890117