In [1]:
import gym
import gym_anm
import time
import numpy as np
from pickle import dump

In [2]:
dataset = []
env = gym.make("gym_anm:ANM6Easy-v0")
state = env.reset()

/Users/carmine/miniforge3/envs/KKT-NN/lib/python3.12/site-packages/gym/utils/passive_env_checker.py:174: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed a `seed` instead of using `Env.seed` for resetting the environment random number generator.
  logger.warn(
/Users/carmine/miniforge3/envs/KKT-NN/lib/python3.12/site-packages/gym/utils/passive_env_checker.py:187: UserWarning: WARN: Future gym versions will require that `Env.reset` can be passed `options` to allow the environment initialisation to be passed additional information.
  logger.warn(
/Users/carmine/miniforge3/envs/KKT-NN/lib/python3.12/site-packages/gym/utils/passive_env_checker.py:195: UserWarning: WARN: The result returned by `env.reset()` was not a tuple of the form `(obs, info)`, where `obs` is a observation and `info` is a dictionary containing additional information. Actual type: `<class 'numpy.ndarray'>`
  logger.warn(


In [3]:
action = env.action_space.sample()
observation, reward, done, info = env.step(action)

/Users/carmine/miniforge3/envs/KKT-NN/lib/python3.12/site-packages/gym/utils/passive_env_checker.py:219: DeprecationWarning: WARN: Core environment is written in old step API which returns one bool instead of two. It is recommended to rewrite the environment with new step API. 
  logger.deprecation(
/Users/carmine/miniforge3/envs/KKT-NN/lib/python3.12/site-packages/gym/utils/passive_env_checker.py:225: DeprecationWarning: `np.bool8` is a deprecated alias for `np.bool_`.  (Deprecated NumPy 1.24)
  if not isinstance(done, (bool, np.bool8)):


In [8]:
env.action_space

Box([  0.   0. -30. -50. -50. -50.], [30. 50. 30. 50. 50. 50.], (6,), float64)

In [26]:
env.simulator.devices[4].p_min

0.0

In [6]:
env.next_vars(state)/100

array([-0.02, -0.2 ,  0.  ,  0.3 ,  0.4 ,  0.58])

In [7]:
state[[1,3,5,2, 4]]/100

array([-0.02, -0.2 ,  0.  ,  0.3 ,  0.4 ])

In [8]:
env.P_maxs[0]

array([ 0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
        0.5       ,  1.        ,  1.5       ,  2.        ,  2.5       ,
        3.        ,  3.5       ,  4.        ,  4.        ,  4.        ,
        4.        ,  4.        ,  4.        ,  4.        ,  4.        ,
        4.        ,  4.        ,  4.        ,  4.        ,  4.        ,
        7.25      , 12.16666667, 17.08333333, 22.        , 26.91666667,
       31.83333333, 36.75      , 30.        , 30.        , 30.        ,
       30.        , 30.        , 30.        , 30.        , 30.        ,
       30.        , 30.        , 30.        , 30.        , 30.        ,
       36.75      , 31.83333333, 26.91666667, 22.        , 17.08

In [9]:
env.P_maxs[1]

array([40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       36.375     , 32.75      , 29.125     , 25.5       , 21.875     ,
       18.25      , 14.625     , 11.        , 11.        , 11.        ,
       11.        , 11.        , 11.        , 11.        , 11.        ,
       11.        , 11.        , 11.        , 11.        , 11.        ,
       14.725     , 18.33333333, 21.94166667, 25.55      , 29.15833333,
       32.76666667, 36.375     , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       40.        , 40.        , 40.        , 40.        , 40.        ,
       36.375     , 32.76666667, 29.15833333, 25.55      , 21.94

In [10]:
env.P_maxs[1].max()

40.0

In [11]:
[
                device[1].p_max * 100
                for device in env.simulator.devices.items()
                if device[1].type == 2
            ]

[30.0, 50.0]

In [12]:
env.action_space.low

array([  0.,   0., -30., -50., -50., -50.])

In [13]:
env.P_maxs/100

array([[0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.        , 0.        , 0.        , 0.        , 0.        ,
        0.005     , 0.01      , 0.015     , 0.02      , 0.025     ,
        0.03      , 0.035     , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      , 0.04      , 0.04      ,
        0.04      , 0.04      , 0.04      , 0.04      , 0.04      ,
        0.0725    , 0.12166667, 0.17083333, 0.22      , 0.26916667,
        0.31833333, 0.3675    , 0.3       , 0.3       , 0.3       ,
        0.3       , 0.3       , 0.3       , 0.3       , 0.3       ,
        0.3       , 0.3       , 0.3       , 0.3       , 0.3       ,
        0.3675    , 0.31833333, 0.26916667, 0.22      , 0.17083333,
        0.12166667, 0.0725    , 0.04      , 0.04

In [24]:
env.simulator.devices[2]

In [15]:
from pickle import load
ds = load(open("dataset_loads.pkl", "rb"))

FileNotFoundError: [Errno 2] No such file or directory: 'dataset_loads.pkl'

In [ ]:
ds[0]

(array([ 2.59981230e+01,  4.07813732e+01, -5.65430813e+00, -4.97427474e+01,
         3.28519440e+01, -1.72633029e+01,  4.00000000e-02,  1.10000000e-01]),
 array([0.04     , 0.11     , 0.0031379]))

In [ ]:
ds = load(open("dataset_loads.pkl", "rb"))
X, y = ds[0]
X = np.array(X)[..., [0,1,2,3,6,7]]
y = np.array(y)[..., [0,1,3,4]]

In [ ]:
actions = X[..., :4]
P_pots = X[...,4:]

In [ ]:
G_val = np.array(
                [
                    [-1, 0, 0, 0],
                    [1, 0, 0 ,0],
                    [1, 0, 0, 0],
                    [0, 0, -1 ,0],
                    [0, 0, 1 ,0],
                    [1.5, 0, 1,0],
                    [1.5, 0, -1, 0],
                    [0, -1,0, 0],
                    [0, 1, 0 ,0],
                    [0, 1, 0, 0],
                    [0, 0, 0 ,-1],
                    [0, 0, 0 ,1],
                    [0, 2.0,0 ,1],
                    [0, 2.0, 0, -1],
                ]
            )

h_val = np.array(
                [
                    [-0.0000, 0.3000, 0.0400, 0.3000, 0.3000, 0.6000, 0.6000, -0.0000, 0.5000,
        0.1100, 0.5000, 0.5000, 1.2000, 1.2000]
                ],
            )

In [ ]:
h_val[..., 2] = P_pots[..., 0]
h_val[..., 9] = P_pots[..., 1]

In [ ]:
action/100

array([ 0.13013569,  0.13316806,  0.08685118,  0.40273407, -0.4556762 ,
        0.08387917])

In [ ]:
P_pots

array([0. , 0.4])

In [ ]:
(np.matmul(G_val, (action[:4]/100).T).T - h_val)

array([[-0.13013569, -0.16986431,  0.13013569, -0.38685118, -0.21314882,
        -0.31794529, -0.49164764, -0.13316806, -0.36683194, -0.26683194,
        -0.90273407, -0.09726593, -0.53092981, -1.33639796]])

In [ ]:
np.maximum((np.matmul(G_val, y.T).T - h_val), 0)

array([[0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 5.55111512e-17, 0.00000000e+00, 0.00000000e+00,
        0.00000000e+00, 0.00000000e+00]])