In [64]:
from pypfopt.expected_returns import mean_historical_return
from pypfopt.risk_models import CovarianceShrinkage
import numpy as np
import pandas as pd
import torch

In [65]:
df = pd.read_csv("stock_prices.csv").drop("date", axis=1)

In [66]:
sector_mapper = {
        "GOOG": "tech",
        "AAPL": "tech",
        "FB": "tech",
        "AMZN": "tech",
        "BABA": "tech",
        "GE": "utility",
        "AMD": "tech",
        "WMT": "retail",
        "BAC": "fig",
        "GM": "auto",
        "T": "auto",
        "UAA": "airline",
        "SHLD": "retail",
        "XOM": "energy",
        "RRC": "energy",
        "BBY": "retail",
        "MA": "fig",
        "PFE": "pharma",
        "JPM": "fig",
        "SBUX": "retail",
    }


In [67]:
#df = df.iloc[:, :20]

In [68]:
mu = mean_historical_return(df)
S = CovarianceShrinkage(df).ledoit_wolf()

In [69]:
tech = mu.iloc[[0,1,2,3,4,6]]
utility = mu.iloc[[5]]
retail = mu.iloc[[7, 12, 15, 19]]
fig = mu.iloc[[8, 16, 18]]
auto = mu.iloc[[9,10]]
airline = mu.iloc[[11]]
energy = mu.iloc[[13, 14]]
pharma = mu.iloc[[17]]

In [70]:
pd.concat([pharma,energy])

PFE    0.226718
XOM    0.143051
RRC    0.073636
dtype: float64

In [71]:
mu

GOOG    0.247967
AAPL    0.294305
FB      0.284037
BABA    0.192316
AMZN    0.371328
GE      0.136009
AMD     0.032850
WMT     0.120012
BAC     0.105540
GM      0.042346
T       0.100256
UAA     0.144224
SHLD   -0.079260
XOM     0.143051
RRC     0.073636
BBY     0.238835
MA      0.388666
PFE     0.226718
JPM     0.156170
SBUX    0.231815
dtype: float64

In [72]:
S

GOOG      AAPL        FB      BABA      AMZN        GE       AMD  \
GOOG  0.045529  0.022143  0.006389  0.003720  0.026085  0.015815  0.021761   
AAPL  0.022143  0.207037  0.004334  0.002954  0.058200  0.038102  0.084053   
FB    0.006389  0.004334  0.029233  0.003770  0.007619  0.003008  0.005804   
BABA  0.003720  0.002954  0.003770  0.013438  0.004176  0.002011  0.006332   
AMZN  0.026085  0.058200  0.007619  0.004176  0.276365  0.038169  0.075657   
GE    0.015815  0.038102  0.003008  0.002011  0.038169  0.083405  0.048580   
AMD   0.021761  0.084053  0.005804  0.006332  0.075657  0.048580  0.388916   
WMT   0.008238  0.026429  0.001243  0.001081  0.027457  0.029076  0.027113   
BAC   0.026957  0.045966  0.004766  0.003077  0.049062  0.062871  0.068272   
GM    0.006163  0.005791  0.003499  0.002573  0.006527  0.007533  0.011758   
T     0.011058  0.019846  0.001395  0.000891  0.018720  0.026464  0.026781   
UAA   0.021371  0.020659  0.009407  0.003461  0.027889  0.025245  0.030291   
SHLD  0.016418  0.022127  0.002191  0.003114  0.027333  0.025666  0.035381   
XOM   0.013362  0.020236  0.002214  0.001751  0.019637  0.025815  0.027946   
RRC   0.018714  0.029179  0.002741  0.002973  0.029789  0.029488  0.049354   
BBY   0.016089  0.048719  0.003813  0.002441  0.059925  0.041375  0.066146   
MA    0.019593  0.019587  0.004727  0.003182  0.023092  0.019308  0.026956   
PFE   0.010683  0.021324  0.002550  0.001624  0.024170  0.029891  0.027965   
JPM   0.023249  0.046814  0.003842  0.002654  0.053367  0.059131  0.069592   
SBUX  0.018075  0.039789  0.004501  0.002162  0.048322  0.034449  0.051764   

           WMT       BAC        GM         T       UAA      SHLD       XOM  \
GOOG  0.008238  0.026957  0.006163  0.011058  0.021371  0.016418  0.013362   
AAPL  0.026429  0.045966  0.005791  0.019846  0.020659  0.022127  0.020236   
FB    0.001243  0.004766  0.003499  0.001395  0.009407  0.002191  0.002214   
BABA  0.001081  0.003077  0.002573  0.000891  0.003461  0.003114  0.001751   
AMZN  0.027457  0.049062  0.006527  0.018720  0.027889  0.027333  0.019637   
GE    0.029076  0.062871  0.007533  0.026464  0.025245  0.025666  0.025815   
AMD   0.027113  0.068272  0.011758  0.026781  0.030291  0.035381  0.027946   
WMT   0.069478  0.030560  0.003595  0.020985  0.012137  0.015605  0.017036   
BAC   0.030560  0.179868  0.012581  0.033848  0.040611  0.039452  0.032159   
GM    0.003595  0.012581  0.021594  0.003942  0.009720  0.011321  0.005865   
T     0.020985  0.033848  0.003942  0.065969  0.013963  0.015191  0.021950   
UAA   0.012137  0.040611  0.009720  0.013963  0.107597  0.035836  0.015710   
SHLD  0.015605  0.039452  0.011321  0.015191  0.035836  0.169301  0.016026   
XOM   0.017036  0.032159  0.005865  0.021950  0.015710  0.016026  0.054884   
RRC   0.012011  0.045077  0.007549  0.019060  0.025306  0.025948  0.039978   
BBY   0.037385  0.052162  0.007759  0.022192  0.028977  0.035722  0.017469   
MA    0.009599  0.035707  0.007317  0.012568  0.024325  0.018643  0.015026   
PFE   0.023160  0.034984  0.004823  0.020900  0.014870  0.014170  0.022466   
JPM   0.033017  0.116165  0.010176  0.035095  0.034874  0.033018  0.030036   
SBUX  0.025482  0.047582  0.006414  0.021491  0.027716  0.026435  0.021248   

           RRC       BBY        MA       PFE       JPM      SBUX  
GOOG  0.018714  0.016089  0.019593  0.010683  0.023249  0.018075  
AAPL  0.029179  0.048719  0.019587  0.021324  0.046814  0.039789  
FB    0.002741  0.003813  0.004727  0.002550  0.003842  0.004501  
BABA  0.002973  0.002441  0.003182  0.001624  0.002654  0.002162  
AMZN  0.029789  0.059925  0.023092  0.024170  0.053367  0.048322  
GE    0.029488  0.041375  0.019308  0.029891  0.059131  0.034449  
AMD   0.049354  0.066146  0.026956  0.027965  0.069592  0.051764  
WMT   0.012011  0.037385  0.009599  0.023160  0.033017  0.025482  
BAC   0.045077  0.052162  0.035707  0.034984  0.116165  0.047582  
GM    0.007549  0.007759  0.007317  0.004823  0.010176  0.0064

In [73]:
max_return = (0.05 * mu.iloc[0] + 0.01*max(utility) +0.01*max(airline) + (1- 0.05 - 0.01  - 0.01)*max(mu))

In [74]:
max_return = (0.05 * mu.iloc[0] + (0.2-0.05)*max(tech)+0.1*max(utility)+0.2*max(retail)+0.4*max(fig)+0.05*max(airline)) +0.2*max(energy) + (1 - 0.2 - 0.1 - 0.2 - 0.4 - 0.05 - 0.2)*max()

TypeError: max expected at least 1 argument, got 0

In [36]:
max_return

0.32075321581485505

In [81]:
from pypfopt.efficient_frontier import EfficientFrontier
import time
sector_upper = {
        "tech": 0.2,
        "utility": 0.1,
        "retail": 0.2,
        "fig": 0.4,
        "airline": 0.05,
        "energy": 0.2}
sector_lower = {"utility": 0.01, "fig": 0.02, "airline": 0.01}

ef = EfficientFrontier(mu, S)
ef.add_sector_constraints(sector_mapper, sector_lower, sector_upper)
ef.add_constraint(lambda x: x[0] == 0.05)
ef.add_constraint(lambda x: x[0] == 0.1)
start = time.time()
ds = []
for rho in np.arange(0.001, 1.0, 0.001):
	weights = ef.max_quadratic_utility(rho)
	ds.append((2*rho - 1, [w for w in list(weights.values())]))
end = time.time()

print(end-start)

2.100224018096924


In [48]:
print(end-start)

0.01583719253540039


In [82]:
ds[0]

(-0.998,
 [0.05,
  0.0,
  0.0,
  0.0,
  0.15,
  0.01,
  0.0,
  0.0,
  0.0,
  0.0,
  0.0,
  0.01,
  0.0,
  0.0,
  0.0,
  0.2,
  0.4,
  0.1799999999999998,
  0.0,
  0.0])

In [122]:
from pickle import dump
dump(ds, open("dataset_stock.pkl", "wb"))

In [123]:
sol = np.array([w/1 for w in list(weights.values())])

In [13]:
S.to_numpy().max()

0.3889155594532419

In [125]:
pred = np.array([sample[-1] for sample in ds])

In [126]:
pred[..., 0]

array([ 2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  2.97268121e-02,  2.97268121e-02,  2.97268121e-02,
        2.97268121e-02,  

In [127]:
pred.std(0)

array([8.39526981e-03, 4.92028944e-03, 5.69528663e-02, 3.75063462e-02,
       6.04739279e-03, 9.31832710e-07, 3.17412503e-06, 1.67960341e-02,
       1.82366214e-06, 8.74222490e-02, 1.80189862e-02, 1.06012822e-06,
       2.16307209e-06, 1.30760388e-02, 1.86978831e-06, 5.35213845e-04,
       8.71545464e-02, 8.53206102e-03, 1.35546920e-06, 1.23816685e-03])

In [128]:
np.linalg.cond(S.to_numpy())

61.96895426563647

In [92]:
matrixSize = 20 
A = np.random.rand(matrixSize, matrixSize)*0.2
B = np.dot(A, A.transpose())

In [93]:
B

array([[0.26832384, 0.20592068, 0.18515731, 0.19809841, 0.1679225 ,
        0.2112639 , 0.24777303, 0.20098326, 0.12727136, 0.15004771,
        0.19114237, 0.23136961, 0.21603114, 0.21329004, 0.23776234,
        0.2100409 , 0.21408915, 0.1581775 , 0.22727505, 0.2201367 ],
       [0.20592068, 0.27443509, 0.20562868, 0.20520585, 0.17005393,
        0.23517279, 0.25257779, 0.20021256, 0.17711055, 0.20395539,
        0.19996511, 0.2590972 , 0.2027577 , 0.23215847, 0.26509914,
        0.25536859, 0.23552735, 0.15158527, 0.21197421, 0.24901373],
       [0.18515731, 0.20562868, 0.24961944, 0.17322798, 0.18022742,
        0.1991135 , 0.25499924, 0.21018195, 0.15617663, 0.16803193,
        0.21077238, 0.2578848 , 0.18495841, 0.20660246, 0.19212372,
        0.20724428, 0.21701992, 0.15204851, 0.22048827, 0.23862087],
       [0.19809841, 0.20520585, 0.17322798, 0.27278208, 0.1456154 ,
        0.23332824, 0.24798999, 0.19180264, 0.16185233, 0.16412075,
        0.18853622, 0.25317167, 0.19609244, 0

In [94]:
np.linalg.cond(B)

228868.54091523492

In [95]:
S.max()

GOOG    0.045529
AAPL    0.207037
FB      0.029233
BABA    0.013438
AMZN    0.276365
GE      0.083405
AMD     0.388916
WMT     0.069478
BAC     0.179868
GM      0.021594
T       0.065969
UAA     0.107597
SHLD    0.169301
XOM     0.054884
RRC     0.242590
BBY     0.268653
MA      0.051108
PFE     0.085783
JPM     0.146781
SBUX    0.139059
dtype: float64

In [96]:
B.min()

0.12444304911729054

In [103]:
A = torch.rand((512, 20, 20))*0.2

In [113]:
torch.bmm(torch.transpose(A, 1, 2), A).flatten(1).shape

torch.Size([512, 400])